-- Create Menu Table
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price BIGINT NOT NULL,
    description TEXT,
    image_url TEXT,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    table_number TEXT,
    items JSONB,
    total_price BIGINT,
    note TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS) - Optional but recommended
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create Policies (Public Read, Authenticated Write for Menu? For now allow all for simplicity or use service key)
-- Allow public read access to menu
CREATE POLICY "Public items are visible to everyone" ON menu_items
    FOR SELECT USING (true);

-- Allow public to insert orders
CREATE POLICY "Public can insert orders" ON orders
    FOR INSERT WITH CHECK (true);

-- Allow public to read their own orders (if we had auth, but here we just allow insert)
